### PR TITLE
Stop sending incorrect parameters for deposit/smash updates

### LINKED ISSUE #7: Inappropriate parameters for deposit.
**Bug Description**

When depositing this dApp sends parameters to the browser wallet, when it shouldn't.
In previous versions this was "ignored" by the wallet, but in the upcoming release, this will now cause the update to be rejected.  

**Steps to Reproduce**

- Use deposit with BW >=v0.9.11.

**Expected Result**

- Transaction can be signed and sent.

**Actual Result**

- Transaction is rejected by the wallet.

### PR DESCRIPTION
**Pull request by shjortConcordium**
## Purpose

Fix #7 (for deposit _and smash_) 

## Changes

No longer send parameters to wallets for  deposit/smash updates

## Checklist

- [x] My code follows the style of this project.
- [x] The code compiles without warnings.
- [x] I have performed a self-review of the changes.
- [x] I have documented my code, in particular the intent of the
      hard-to-understand areas.
- [ ] (If necessary) I have updated the CHANGELOG.

### CODE REVIEW

**Comment by bisgardo** [comment]
This change requires an update of the wallet-connectors dapp library to work with walletconnect:

```
cannot submit deposit transaction: parameters provided for 'Update' transaction must be not undefined
```

**Comment by bisgardo** [comment]
> This change requires an update of the wallet-connectors dapp library to work with walletconnect:
> 
> ```
> cannot submit deposit transaction: parameters provided for 'Update' transaction must be not undefined
> ```
> 
> I'll look into it.

Done in https://github.com/Concordium/concordium-dapp-libraries/pull/34.

**Review by bisgardo — APPROVED** [review]

**Comment by arslanpixpel** [comment]
Hi I'm calling payable function and using piggyBank dapp

I'm using web-sdk for frontend.
When I'm providing RAW_SCHEMA it says JSON string required when I remove it says parsing error

```
function contractUpdatePayload(amount: CcdAmount, contract: Info, method: string) {
    return {
        amount,
        address: {
            index: contract.index,
            subindex: BigInt(0),
        },
        receiveName: `${contract.name}.${method}`,
        maxContractExecutionEnergy: MAX_CONTRACT_EXECUTION_ENERGY,
    };
}

export async function submitDeposit(connection: WalletConnection, amount: CcdAmount, account: string, contract: Info) {
    const buff = toBuffer(RAW_SCHEMA_W, 'base64');
    // const seerial = serializeTypeValue(params, buff);
    // console.log(JSON.stringify(RAW_SCHEMA));
    // const sch = JSON.stringify(RAW_SCHEMA);
    // const param = JSON.stringify(account);
    const param = { User: '3v6SAaexxQ4zwi5AwAncD4yTLtMSXuB9PC7v4dEwu5arMuRRsW' };
    return connection.signAndSendTransaction(
        account,
        AccountTransactionType.Update,
        contractUpdatePayload(amount, contract, 'vest'),
        { params },
        RAW_SCHEMA_W
    );
}
```

**Comment by shjortConcordium** [comment]
> 

Hi @arslanpixpel,

You are giving incorrect parameters (I assume you don't need to provide an object like { params: { User: '...' } })
Please create an issue or write on our support forum if this is still an issue forum.

**Pull request merged**
